// Autogenerated Legal Documents Data for Krayam (Operated by Aurions)
// Last Updated: 14 September 2026

export interface LegalSection {
  heading: string;
  body: string;
}

export interface LegalDocument {
  title: string;
  lastUpdated: string;
  effectiveDate: string;
  operator: string;
  preamble: string;
  sections: LegalSection[];
}

export const TERMS_AND_CONDITIONS_DATA: LegalDocument = {
  title: 'Terms & Conditions',
  lastUpdated: '14 September 2026',
  effectiveDate: '14 September 2026',
  operator: 'Aurions',
  preamble: "# Terms & Conditions\r\n\r\n**Last Updated:** 14 September 2026\r\n**Effective Date:** 14 September 2026\r\n\r\nWelcome to **Krayam**, a digital farmer procurement platform operated by **Aurions** (\"Aurions\", \"we\", \"us\", or \"our\").\r\n\r\nKrayam provides digital services that help farmers register, locate procurement centres, create procurement bookings, select available slots, track queues, monitor procurement, view payment information, and receive service notifications through mobile, web, and SMS interfaces.\r\n\r\nBy accessing or using Krayam, you agree to these Terms & Conditions.",
  sections: [
  {
    "heading": "1. Eligibility and Registration",
    "body": "Farmers must provide accurate and complete information when registering or using Krayam.\r\n\r\nThis may include:\r\n\r\n* Name\r\n* Mobile number\r\n* Farmer ID\r\n* Village and location\r\n* Language preference\r\n* Crop and procurement information\r\n\r\nUsers must not register using another person's identity or knowingly provide false information.\r\n\r\nCentre operators may use operator functionality only when authorized by Aurions or the relevant procurement organization."
  },
  {
    "heading": "2. Account and Security",
    "body": "Users are responsible for maintaining the security of their account and authentication information.\r\n\r\nUsers must not:\r\n\r\n* share their account with unauthorized persons;\r\n* use another person's account;\r\n* attempt to bypass authentication;\r\n* create fraudulent accounts;\r\n* impersonate another farmer or operator.\r\n\r\nAny suspected unauthorized access should be reported to Aurions immediately.\r\n\r\nAurions may suspend or restrict accounts involved in fraudulent, abusive, or unlawful activity."
  },
  {
    "heading": "3. Farmer Procurement Services",
    "body": "Krayam may allow farmers to:\r\n\r\n* select crops;\r\n* enter procurement quantities;\r\n* select expected procurement dates;\r\n* use their current location;\r\n* find recommended procurement centres;\r\n* compare alternative centres;\r\n* view centre queues;\r\n* view estimated waiting times;\r\n* view centre capacity or load;\r\n* select procurement slots;\r\n* create bookings;\r\n* cancel bookings;\r\n* reschedule bookings where permitted;\r\n* track procurement;\r\n* view payment information;\r\n* receive notifications.\r\n\r\nAvailability of these services may depend on centre capacity, procurement rules, system availability, connectivity, and operational conditions."
  },
  {
    "heading": "4. Centre Recommendations",
    "body": "Krayam may recommend procurement centres using factors such as:\r\n\r\n* distance;\r\n* current queue;\r\n* estimated waiting time;\r\n* centre capacity;\r\n* accepted crops;\r\n* expected load;\r\n* historical and operational information.\r\n\r\nCentre recommendations are intended to assist farmers and do not guarantee that a particular centre will accept a farmer or a particular quantity."
  },
  {
    "heading": "5. Booking Policy",
    "body": "A booking represents a procurement request or allocated slot according to the Krayam booking system.\r\n\r\nA booking does not necessarily guarantee acceptance of the entire quantity entered by the farmer.\r\n\r\nActual acceptance may depend on:\r\n\r\n* crop eligibility;\r\n* centre capacity;\r\n* applicable procurement rules;\r\n* quality requirements;\r\n* verification;\r\n* actual quantity presented;\r\n* operational conditions."
  },
  {
    "heading": "6. Cancellation and Rescheduling",
    "body": "Farmers may cancel or reschedule bookings where the relevant functionality is available.\r\n\r\nCancellation or rescheduling may be restricted after an applicable cutoff time.\r\n\r\nRescheduling is subject to available slots and centre capacity.\r\n\r\nA procurement centre may modify or cancel a booking because of:\r\n\r\n* capacity limitations;\r\n* operational disruptions;\r\n* technical problems;\r\n* centre closure;\r\n* crop restrictions;\r\n* emergency circumstances;\r\n* applicable procurement requirements.\r\n\r\nWhere reasonably possible, affected farmers will be notified."
  },
  {
    "heading": "7. No-Show Policy",
    "body": "If a farmer does not arrive for a confirmed procurement slot, the booking may be marked as a **No-Show**.\r\n\r\nRepeated no-shows may affect future booking availability where permitted by applicable operational rules."
  },
  {
    "heading": "8. Queue and Waiting-Time Information",
    "body": "Krayam may display:\r\n\r\n* current queue position;\r\n* number of farmers ahead;\r\n* estimated waiting time;\r\n* queue progress;\r\n* estimated turn time.\r\n\r\nQueue information may change continuously.\r\n\r\nEstimated waiting times are predictions and are not guarantees.\r\n\r\nActual waiting time may be affected by:\r\n\r\n* farmer arrivals;\r\n* processing speed;\r\n* quantity;\r\n* quality checks;\r\n* technical problems;\r\n* staff availability;\r\n* centre capacity;\r\n* operational interruptions."
  },
  {
    "heading": "9. Procurement Policy",
    "body": "The actual quantity accepted by a procurement centre may differ from the booked quantity.\r\n\r\nThe final procurement record shall be based on information recorded and verified by the authorized procurement centre.\r\n\r\nWhere applicable, the centre may record:\r\n\r\n* accepted quantity;\r\n* procurement status;\r\n* quality or status information;\r\n* applicable rate;\r\n* payable amount;\r\n* procurement completion."
  },
  {
    "heading": "10. Payment Policy",
    "body": "Krayam may display:\r\n\r\n* booked quantity;\r\n* accepted quantity;\r\n* applicable rate;\r\n* calculated payment amount;\r\n* payment status;\r\n* payment reference;\r\n* payment history.\r\n\r\nWhere applicable:\r\n\r\n**Payable Amount = Accepted Quantity × Applicable Rate**\r\n\r\nAdditional adjustments or deductions may apply according to applicable procurement rules.\r\n\r\nPayments may be processed by an authorized organization, government authority, bank, or payment service provider.\r\n\r\nKrayam may display payment status but does not guarantee the processing time of a third-party payment system."
  },
  {
    "heading": "11. Refund and Dispute Policy",
    "body": "Where a refund is applicable, it shall be handled according to the applicable procurement, payment, or organizational rules.\r\n\r\nKrayam may not be responsible for refunds controlled entirely by an external procurement authority, bank, or payment provider.\r\n\r\nFarmers may raise disputes regarding:\r\n\r\n* booking information;\r\n* accepted quantity;\r\n* payment amount;\r\n* payment status;\r\n* cancellation;\r\n* procurement records;\r\n* technical issues.\r\n\r\nUsers should provide their Farmer ID, Booking ID, Procurement ID, payment reference, and relevant details when submitting a dispute."
  },
  {
    "heading": "12. SMS Services",
    "body": "Krayam may provide procurement services through SMS.\r\n\r\nSupported commands may include:\r\n\r\n* REGISTER\r\n* BOOK\r\n* STATUS\r\n* QUEUE\r\n* CENTRE\r\n* PAYMENT\r\n* HISTORY\r\n* CANCEL\r\n* RESCHEDULE\r\n* HELP\r\n\r\nFarmers may also send natural-language messages.\r\n\r\nFor example:\r\n\r\n> \"Mujhe 30 quintal gehun bechna hai 15 September ko\"\r\n\r\nThe system may identify the booking intent, crop, quantity, and date.\r\n\r\nThe system may request confirmation before creating a booking.\r\n\r\nUsers are responsible for verifying automatically interpreted information.\r\n\r\nSMS delivery may be delayed or unavailable because of:\r\n\r\n* telecom network issues;\r\n* incorrect mobile numbers;\r\n* operator issues;\r\n* technical failures;\r\n* device limitations.\r\n\r\nNormal telecom or SMS charges may apply according to the user's mobile operator."
  },
  {
    "heading": "13. AI and Automated Decision-Making",
    "body": "Krayam may use artificial intelligence and machine-learning systems for:\r\n\r\n* centre recommendations;\r\n* waiting-time prediction;\r\n* expected farmer arrivals;\r\n* centre-load prediction;\r\n* demand forecasting;\r\n* slot recommendations;\r\n* anomaly detection;\r\n* natural-language SMS processing.\r\n\r\nAI-generated results are estimates and may contain errors.\r\n\r\nAI recommendations do not guarantee:\r\n\r\n* centre availability;\r\n* waiting time;\r\n* procurement acceptance;\r\n* payment timing;\r\n* booking availability.\r\n\r\nWhere required, authorized personnel may review or override automated recommendations."
  },
  {
    "heading": "14. Location and GPS Usage",
    "body": "Krayam may request access to device location to:\r\n\r\n* identify nearby centres;\r\n* calculate distance;\r\n* recommend procurement centres;\r\n* support navigation;\r\n* improve location-based services.\r\n\r\nUsers may deny location permission and manually provide location where supported.\r\n\r\nDisabling location access may limit certain Krayam features.\r\n\r\nGPS and other location technologies may not always provide perfectly accurate information.\r\n\r\nLocation information is handled according to the Krayam Privacy Policy."
  },
  {
    "heading": "15. Notifications and Communications",
    "body": "Krayam may send service-related communications through:\r\n\r\n* SMS;\r\n* mobile notifications;\r\n* web notifications;\r\n* email, where applicable.\r\n\r\nNotifications may include:\r\n\r\n* registration confirmation;\r\n* booking confirmation;\r\n* booking reminders;\r\n* slot reminders;\r\n* queue updates;\r\n* ETA updates;\r\n* turn-approaching alerts;\r\n* procurement completion;\r\n* payment initiated;\r\n* payment confirmation;\r\n* important operational announcements.\r\n\r\nEssential service communications may continue where necessary to provide requested services."
  },
  {
    "heading": "16. Acceptable Use Policy",
    "body": "Users must use Krayam lawfully and responsibly.\r\n\r\nUsers must not:\r\n\r\n* create fraudulent bookings;\r\n* manipulate queue positions;\r\n* submit false information;\r\n* impersonate another user;\r\n* access another user's account;\r\n* attempt unauthorized system access;\r\n* introduce malware;\r\n* interfere with Platform operations;\r\n* scrape Platform data without authorization;\r\n* misuse SMS services;\r\n* manipulate AI systems;\r\n* misuse farmer or operator information;\r\n* use Krayam for unlawful activities.\r\n\r\nViolation of these rules may result in account suspension, booking cancellation, access restrictions, or other appropriate action."
  },
  {
    "heading": "17. Grievance Redressal",
    "body": "Users may submit complaints relating to:\r\n\r\n* registration;\r\n* booking;\r\n* cancellation;\r\n* rescheduling;\r\n* queue management;\r\n* procurement;\r\n* payments;\r\n* SMS services;\r\n* privacy;\r\n* account access;\r\n* operator conduct;\r\n* accessibility;\r\n* technical issues.\r\n\r\nComplaints may be submitted through the support and grievance mechanisms provided by Krayam.\r\n\r\nAurions will review complaints and take appropriate action according to their nature and applicable requirements."
  },
  {
    "heading": "18. Accessibility Statement",
    "body": "Aurions aims to make Krayam accessible to users with different levels of digital literacy and abilities.\r\n\r\nKrayam aims to provide:\r\n\r\n* readable text;\r\n* clear navigation;\r\n* responsive interfaces;\r\n* accessible forms;\r\n* meaningful error messages;\r\n* multilingual functionality where supported;\r\n* mobile-friendly design;\r\n* SMS-based alternatives where supported."
  },
  {
    "heading": "19. Intellectual Property and Copyright",
    "body": "Krayam's software, source code, interface, design, graphics, logos, trademarks, documentation, databases, and other original materials are owned by or licensed to Aurions unless otherwise stated.\r\n\r\nUsers may not reproduce, distribute, modify, reverse engineer, commercially exploit, or create derivative works from Krayam materials without authorization.\r\n\r\nNothing in these Terms transfers ownership of Krayam or Aurions intellectual property to the user."
  },
  {
    "heading": "20. User-Provided Information",
    "body": "Users are responsible for the information they submit to Krayam.\r\n\r\nUsers confirm that they have the right to provide such information and that it is not intentionally false or unlawful.\r\n\r\nAurions may process submitted information for providing requested services in accordance with the Privacy Policy."
  },
  {
    "heading": "21. Third-Party Services",
    "body": "Krayam may depend on third-party services including:\r\n\r\n* SMS gateways;\r\n* payment providers;\r\n* mapping services;\r\n* cloud infrastructure;\r\n* authentication providers;\r\n* analytics services;\r\n* AI services.\r\n\r\nThird-party services may have their own terms and privacy policies.\r\n\r\nAurions is not responsible for failures entirely caused by third-party systems, subject to applicable law."
  },
  {
    "heading": "22. Offline Mode",
    "body": "The Centre Operator interface may provide limited functionality when connectivity is unavailable.\r\n\r\nOperators may be able to:\r\n\r\n* access previously synchronized bookings;\r\n* check in farmers;\r\n* manage queues;\r\n* start processing;\r\n* complete processing;\r\n* record accepted quantities;\r\n* prepare payment information.\r\n\r\nOffline actions may be stored locally until synchronization becomes available.\r\n\r\nPayment confirmation and SMS notifications may remain pending until successful synchronization with the backend."
  },
  {
    "heading": "23. System Availability",
    "body": "Aurions aims to provide reliable services but does not guarantee uninterrupted availability.\r\n\r\nServices may be unavailable because of:\r\n\r\n* maintenance;\r\n* network failures;\r\n* power failures;\r\n* server failures;\r\n* cybersecurity incidents;\r\n* third-party service failures;\r\n* natural disasters;\r\n* government restrictions;\r\n* other circumstances beyond reasonable control."
  },
  {
    "heading": "24. General Disclaimer",
    "body": "Information displayed by Krayam may include estimated, predicted, or dynamically changing information.\r\n\r\nThis includes:\r\n\r\n* queue position;\r\n* waiting time;\r\n* centre load;\r\n* centre recommendations;\r\n* availability;\r\n* demand forecasts;\r\n* AI predictions;\r\n* payment status.\r\n\r\nSuch information should not be treated as an absolute guarantee.\r\n\r\nActual procurement remains subject to applicable rules, verification, centre operations, capacity, crop eligibility, quality requirements, and other applicable conditions."
  },
  {
    "heading": "25. Privacy",
    "body": "Personal information is handled according to the Krayam Privacy Policy.\r\n\r\nThe Privacy Policy explains:\r\n\r\n* information collected;\r\n* purposes of processing;\r\n* data sharing;\r\n* location processing;\r\n* AI processing;\r\n* retention;\r\n* security;\r\n* user rights;\r\n* grievance mechanisms."
  },
  {
    "heading": "26. Suspension and Termination",
    "body": "Aurions may restrict, suspend, or terminate access where necessary because of:\r\n\r\n* fraud;\r\n* abuse;\r\n* security concerns;\r\n* violation of these Terms;\r\n* unlawful activity;\r\n* operational requirements.\r\n\r\nWhere appropriate and legally required, users may be provided an opportunity to resolve the issue."
  },
  {
    "heading": "27. Changes to Terms",
    "body": "Aurions may update these Terms from time to time.\r\n\r\nUpdated Terms will be published through Krayam.\r\n\r\nWhere required, significant changes may be communicated to users."
  },
  {
    "heading": "28. Governing Law",
    "body": "These Terms shall be governed by applicable laws of India.\r\n\r\nDisputes shall be handled by the appropriate courts or authorities having jurisdiction, subject to applicable law."
  },
  {
    "heading": "29. Contact",
    "body": "**Aurions**\r\n\r\nKrayam Support and Grievance Services are available through the contact channels provided within the Platform."
  },
  {
    "heading": "30. Acceptance",
    "body": "By selecting **\"I Agree\"**, registering, or using Krayam, you acknowledge that you have read and agree to these Terms & Conditions."
  }
]
};

export const COOKIE_POLICY_DATA: LegalDocument = {
  title: 'Cookie Policy',
  lastUpdated: '14 September 2026',
  effectiveDate: '14 September 2026',
  operator: 'Aurions',
  preamble: "# Cookie Policy\r\n\r\n**Last Updated:** 14 September 2026\r\n\r\nKrayam uses cookies and similar technologies on its website to provide essential functionality, maintain security, remember preferences, and understand how the website is used.",
  sections: [
  {
    "heading": "1. What Are Cookies?",
    "body": "Cookies are small files or pieces of information stored on your device when you visit a website.\r\n\r\nThey may help websites:\r\n\r\n* maintain login sessions;\r\n* remember preferences;\r\n* provide security;\r\n* measure website usage;\r\n* improve functionality."
  },
  {
    "heading": "2. Types of Cookies",
    "body": "### 2.1 Essential Cookies\r\n\r\nEssential cookies are required for core website functionality.\r\n\r\nThey may be used for:\r\n\r\n* authentication;\r\n* login sessions;\r\n* security;\r\n* fraud prevention;\r\n* session management;\r\n* basic Platform functionality.\r\n\r\nThese cookies may remain active because they are necessary for the secure operation of Krayam.\r\n\r\n### 2.2 Preference Cookies\r\n\r\nPreference cookies may remember choices such as:\r\n\r\n* selected language;\r\n* interface preferences;\r\n* previously selected settings.\r\n\r\n### 2.3 Analytics Cookies\r\n\r\nWhere enabled, analytics cookies may help Aurions understand:\r\n\r\n* which pages are used;\r\n* how users navigate Krayam;\r\n* website performance;\r\n* errors;\r\n* general feature usage.\r\n\r\nAnalytics information may be used to improve Krayam.\r\n\r\n### 2.4 Third-Party Cookies\r\n\r\nCertain third-party services integrated with Krayam may use cookies or similar technologies.\r\n\r\nThese services may support:\r\n\r\n* analytics;\r\n* maps;\r\n* security;\r\n* authentication;\r\n* other Platform functionality.\r\n\r\nThird-party processing may be subject to the respective provider's policies."
  },
  {
    "heading": "3. Your Cookie Choices",
    "body": "When you first visit Krayam, you may choose from the following options:\r\n\r\n### Accept All\r\n\r\nAllows essential cookies and optional cookies, including preference and analytics cookies where applicable.\r\n\r\n### Accept Only Essential Cookies\r\n\r\nAllows only cookies required for the basic functioning and security of Krayam.\r\n\r\nOptional cookies, including analytics or preference cookies that require consent, will not be enabled.\r\n\r\n### Do Not Accept\r\n\r\nDeclines optional cookies.\r\n\r\nEssential cookies may still be used where necessary for Krayam to function securely."
  },
  {
    "heading": "4. Cookie Consent",
    "body": "Your selected cookie preference may be stored so that Krayam does not repeatedly display the cookie consent notice.\r\n\r\nWhere supported, you may change your cookie preferences later."
  },
  {
    "heading": "5. Browser Controls",
    "body": "You may also manage or delete cookies through your browser settings.\r\n\r\nDisabling essential cookies may cause certain Krayam features to stop functioning."
  },
  {
    "heading": "6. Changes to this Policy",
    "body": "Aurions may update this Cookie Policy when cookie usage or applicable requirements change.\r\n\r\nThe latest version will be published through Krayam."
  },
  {
    "heading": "7. Contact",
    "body": "For questions regarding cookies and similar technologies, users may contact Aurions through the privacy and support channels available through Krayam."
  }
]
};

export const PRIVACY_POLICY_DATA: LegalDocument = {
  title: 'Privacy Policy',
  lastUpdated: '14 September 2026',
  effectiveDate: '14 September 2026',
  operator: 'Aurions',
  preamble: 'Welcome to Krayam, a digital farmer procurement platform operated by Aurions ("Aurions", "we", "us", or "our"). This Privacy Policy describes how we collect, use, disclose, protect, and handle your personal, agricultural, and financial information when you access or use the Krayam portal, mobile applications, SMS services, and procurement centre terminals.',
  sections: [
  {
    "heading": "1. Information We Collect",
    "body": "Krayam collects personal, agricultural, and operational data necessary to facilitate farmer procurement, mandi slot scheduling, and direct payment processing:\n\n* **Identity & Contact Information:** Name, mobile phone number, Farmer ID, village, tehsil, district, state, and postal code.\n* **Agricultural & Land Data:** Landholding size (in acres), primary and secondary crop varieties sown, estimated harvest quantity, and seasonal production estimates.\n* **Banking & DBT Details:** Bank account holder name, bank branch, account number, and IFSC code for direct benefit transfer (DBT) and MSP disbursements.\n* **Aadhaar & Verification Details:** Masked Aadhaar number or demographic verification details strictly handled under the Aadhaar Act and applicable data protection regulations.\n* **Telemetry & Weighbridge Data:** Vehicle registration number, gross weight, tare weight, net crop yield, moisture content percentages, foreign matter analysis, and quality deductions.\n* **Geolocation Data:** Precise or approximate GPS coordinates collected with user consent to calculate real-time driving distances and recommend optimal procurement centres."
  },
  {
    "heading": "2. How We Use Your Information",
    "body": "Information collected by Krayam is used exclusively for legitimate agricultural procurement operations:\n\n* Processing mandi slot bookings, token allocations, and gate pass generation.\n* Live queue scheduling and dynamic wait-time estimation.\n* Weighbridge telemetry integration and automated J-Form / procurement certificate creation.\n* Transmitting Direct Benefit Transfer (DBT) payment mandates to Public Financial Management System (PFMS) and commercial banks.\n* Delivering critical SMS alerts, booking confirmations, queue advance reminders, and payment settlement notifications.\n* Aggregated analytics for state food supply planning and procurement monitoring."
  },
  {
    "heading": "3. Data Sharing and Disclosure",
    "body": "Aurions does not sell, rent, or trade farmers' personal or financial data to third-party commercial marketing entities. Data may be shared strictly with:\n\n* **Government & Procurement Bodies:** Food Corporation of India (FCI), State Civil Supplies Departments, Agricultural Produce Market Committees (APMC), and authorized mandi officials.\n* **Financial Infrastructure:** Reserve Bank of India (RBI) regulated commercial banks, National Payments Corporation of India (NPCI), and PFMS for processing MSP payouts.\n* **Authorized Service Providers:** Cloud infrastructure providers, telecom SMS gateways, and secure mapping APIs bound by strict data confidentiality agreements.\n* **Legal Obligations:** When mandated by Indian law, judicial decree, or authorized statutory government notices."
  },
  {
    "heading": "4. Data Protection and Aadhaar Security",
    "body": "We implement industry-standard administrative, physical, and technical safeguards:\n\n* **Encryption:** All data in transit is protected using TLS 1.3 encryption, and sensitive fields (such as banking data) are encrypted at rest using AES-256.\n* **Aadhaar Masking:** Aadhaar numbers are masked so that only the last 4 digits are visible to mandi operators or support personnel. Full biometric data is never stored on Krayam servers.\n* **Strict Role-Based Access Control (RBAC):** Mandi operators and supervisors only access data for farmers scheduled at their assigned physical procurement centre."
  },
  {
    "heading": "5. Data Retention",
    "body": "Procurement records, J-Forms, weighbridge receipts, and DBT payment logs are retained in accordance with statutory government agricultural procurement rules, auditing requirements, and applicable Indian record retention guidelines. Farmers may access historical transaction receipts indefinitely through their portal account."
  },
  {
    "heading": "6. Farmers' Rights and Choices",
    "body": "Every registered farmer holds rights over their personal data:\n\n* **Access and Portability:** View and download your complete booking history, gate passes, lab quality slips, and payment vouchers.\n* **Rectification:** Update personal mobile numbers, residential addresses, and banking information through profile settings or mandi helpdesks.\n* **Communication Preferences:** Customize language preferences across 11 official Indian languages for portal navigation and SMS notifications."
  },
  {
    "heading": "7. Cookies and Tracking Technologies",
    "body": "Krayam uses cookies and localized browser storage to maintain secure login sessions, retain language selection, and record offline sync queues. For detailed information, please review our **Cookie Policy**."
  },
  {
    "heading": "8. Changes to this Privacy Policy",
    "body": "Aurions may update this Privacy Policy to reflect changes in regulatory standards or platform enhancements. Significant amendments will be announced via platform banners or SMS notifications."
  },
  {
    "heading": "9. Grievance Redressal and Contact",
    "body": "For privacy inquiries, grievance submissions, or data protection concerns, farmers may contact the Aurions Grievance Redressal Officer:\n\n* **Entity:** Aurions (Krayam Procurement Division)\n* **Kisan Toll-Free Support:** 1800-180-1551 (06:00 AM - 10:00 PM, 365 Days)\n* **Email:** privacy@aurions.krayam.gov.in / support@krayam.in\n* **Headquarters:** National Informatics Centre / Ministry of Agriculture & Farmers Welfare, Krishi Bhawan, New Delhi - 110001"
  }
]
};
